name: haven
description: Private, forward-secret family location sharing.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
