name: haven
description: Private, forward-secret family location sharing.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.11.1
  rust_lib_haven:
    path: rust_builder

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0
  integration_test:
    sdk: flutter
  ffigen: ^20.1.1

flutter:
  uses-material-design: true
