[package]
name = "rust_lib_haven"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
haven-core = { path = "../../haven-core" }
flutter_rust_bridge = "=2.11.1"
